services:
  database:
    image: postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_MULTIPLE_DATABASES: ecommerce_auth,ecommerce_product,ecommerce_cart,ecommerce_order
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  event-bus:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: retrair
      RABBITMQ_DEFAULT_PASS: 12345
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3

  api-gateway:
    build:
      context: ./src/ApiGateway/Ocelot.API.Gateway
    ports:
      - 8080:80
    depends_on:
      - auth-api
      - product-api
      - cart-api
      - payment-api
      - order-api
      
  auth-api:
    build: 
      context: ./src/Services/Auth/Auth.API
    depends_on:
      database:
        condition: service_healthy

  product-api:
    build: 
      context: ./src/Services/Products/Products.API
    depends_on:
      database:
        condition: service_healthy

  cart-api:
    build: 
      context: ./src/Services/Carts/Carts.API
    depends_on:
      - product-api
  
  payment-api:
    build:
      context: ./src/Services/Payment/Payment.API
    depends_on:
      event-bus:
        condition: service_healthy

  order-api:
    build:
      context: ./src/Services/Order/Order.API
    depends_on:
      database:
        condition: service_healthy
      event-bus:
        condition: service_healthy

  web:
    build:
      context: ./src/Web/
    ports:
      - 5000:5000
    depends_on:
      - api-gateway
